# Generated by Django 4.0.6 on 2023-02-02 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ')),
                ('date_modified', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', related_query_name='get_posts', to=settings.AUTH_USER_MODEL, verbose_name='پست')),
                ('subject', models.ManyToManyField(related_name='post_subject', to='blog.subject')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
