# Generated by Django 4.0.6 on 2022-12-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_pot_potpic'),
        ('orders', '0004_service_order_change_pot_order_change_soil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pot', related_query_name='get_pots', to='products.pot', verbose_name='گلدان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='get_orders', to='products.product', verbose_name='محصول'),
        ),
    ]
