# Generated by Django 4.0.6 on 2022-12-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_factor_order_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='factor_final_price',
            field=models.IntegerField(default=0),
        ),
    ]
