# Generated by Django 4.0.6 on 2023-01-03 14:54

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='d',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
