# Generated by Django 4.0.6 on 2023-01-03 14:55

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='d',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
