# Generated by Django 4.0.6 on 2023-01-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_address'),
        ('orders', '0015_alter_factor_factor_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facotraddress', related_query_name='get_address', to='users.address', verbose_name='ادرس'),
        ),
    ]
