# Generated by Django 4.0.6 on 2023-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_factor_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
    ]
