# Generated by Django 4.0.6 on 2023-01-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_factor_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='روش')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='بها')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش های ارسال',
            },
        ),
    ]
