# Generated by Django 4.0.6 on 2023-02-14 13:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_shipped_date_alter_factor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='d',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=django_jalali.db.models.jDateField(auto_now=True, null=True, verbose_name='تاریخ ارسال'),
        ),
    ]
