# Generated by Django 4.0.6 on 2023-02-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_factor_d_alter_order_shipped_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped_date',
        ),
    ]
