# Generated by Django 4.0.6 on 2023-02-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_order_shipped_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='date',
        ),
    ]
