# Generated by Django 4.0.6 on 2023-02-14 13:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_factor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ فاکتور'),
        ),
    ]
