# Generated by Django 4.0.6 on 2023-02-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_factor_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(max_length=50)),
                ('verf_track_id', models.CharField(max_length=50, null=True)),
                ('track_id', models.CharField(max_length=50, null=True)),
                ('pay_link', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10, null=True)),
                ('order_id', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('factor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.factor')),
            ],
        ),
    ]
