# Generated by Django 4.0.6 on 2023-02-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_address'),
        ('orders', '0024_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facotraddress', related_query_name='get_address', to='users.address', verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='factor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.factor'),
        ),
    ]
