# Generated by Django 4.0.6 on 2023-02-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_factor_to_alter_payment_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'رسید پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='get_orders', to='orders.factor', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='factor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.factor', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=50, verbose_name='ایدی سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_id',
            field=models.CharField(max_length=50, verbose_name='ایدی رسید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_link',
            field=models.CharField(max_length=200, verbose_name='لینک پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=10, null=True, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ایدی پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verf_track_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ایدی استعلام پرداخت'),
        ),
    ]
