# Generated by Django 4.0.6 on 2022-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('is_avail', models.BooleanField(verbose_name='موجود')),
                ('is_new', models.BooleanField(default=False)),
                ('is_off', models.BooleanField(default=False, verbose_name='تخفیف خورده')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
