# Generated by Django 4.0.6 on 2022-12-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_caption_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpic',
            name='r_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='products.product'),
        ),
    ]
