# Generated by Django 4.0.6 on 2022-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productpic_r_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productpic',
            options={'verbose_name': ' عکس محصول', 'verbose_name_plural': 'گالری محصولات'},
        ),
        migrations.RenameField(
            model_name='productpic',
            old_name='r_product',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='main_pic',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
    ]
