# Generated by Django 4.0.6 on 2022-12-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_productpic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_pic',
            field=models.ImageField(null=True, upload_to='media/product', verbose_name='تصویر اصلی'),
        ),
    ]
