# Generated by Django 4.0.6 on 2023-01-03 15:10

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_pot_potpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='d',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AddField(
            model_name='product',
            name='d',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ میلادی'),
        ),
    ]
