# Generated by Django 4.0.6 on 2023-01-05 15:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pot_d_product_d_alter_pot_date_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='d',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
    ]
