# Generated by Django 4.0.6 on 2023-02-05 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_alter_pot_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='آی پی کاربر')),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_costumer', related_query_name='get_visiting_customers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بازدید کننده')),
                ('pot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pot_visits', to='products.pot', verbose_name='بازدید گلدان ها')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_visits', to='products.product', verbose_name='بازدید محصولات')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدید ها',
            },
        ),
    ]
